#!/bin/bash

# add path to surface_tools
export Path=$PATH:/data/pt_02319/Anna/MPC/surface_tools-master/equivolumetric_surfaces/

# set up as overearching bids directory
dataDir=/data/pt_02319/Anna/MPC/datalad_project/DataLad-101/human-connectome-project-openaccess/HCP1200

# change to your subject list
input="/data/pt_02319/Anna/MPC/01_constructSurfaces/fulllist.txt"
#/data/pt_02319/Anna/MPC/01_constructSurfaces/fulllist_LS.txt | \ 
while IFS= read -r sub ; do   

 # Set up SUBJECTS_DIR for freesurfer based functions 
    # In this setup the freesurfer output is nested within 'surfaces' 
    # subdirectory of the subject's BIDS folder
    export SUBJECTS_DIR=${dataDir}/${sub}/T1w
    
		# setup output directory
		outDir=/data/pt_02319/Anna/MPC/01_constructSurfaces/HCP/${sub}/surfaces/equivSurfs
		
		# checks whether the output directory exists and makes it if it doesn't
		[[ ! -d "$outDir" ]] && mkdir -p "$outDir"

		# best practice to construct multiple sets of surfaces, with a range of surface numbers for optimisation
		
		for num_surfs in $(seq 10 1 30) ; do

			# set output directory and create directory if necessary
			[[ ! -d "$outDir"/"$num_surfs"surfs ]] && mkdir -p "$outDir"/"$num_surfs"surfs

			for hemi in lh rh ; do
			
				python /data/pt_02319/Anna/MPC/surface_tools-master/equivolumetric_surfaces/generate_equivolumetric_surfaces.py \
				"$dataDir"/${sub}/T1w/${sub}/surf/"$hemi".pial \
				"$dataDir"/${sub}/T1w/${sub}/surf/"$hemi".white \
				"$num_surfs" \
				"$outDir"/"$num_surfs"surfs/"$hemi"_equiv_"$num_surfs"surfs \
                                --software freesurfer \
				--subject "$sub"
            done
            
        done

done < "$input"
